/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

public class Buscar extends javax.swing.JFrame {

    public JPanel getJpanelBuscarUsuario() {
        return jpanelBuscarUsuario;
    }

    public JTable getJbBuscar() {
        return jbBuscar;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 61 * hash + Objects.hashCode(this.jtBuscarcliente);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Buscar other = (Buscar) obj;
        return true;
    }

    public void setJbBuscar(JTable jbBuscar) {
        this.jbBuscar = jbBuscar;
    }

    public void setJpanelBuscarUsuario(JPanel jpanelBuscarUsuario) {
        this.jpanelBuscarUsuario = jpanelBuscarUsuario;
    }

    public JButton getJtBuscarcliente() {
        return jtBuscarcliente;
    }

    @Override
    public String toString() {
        return "Buscar{" + "Buscar=" + Buscar + ", jScrollPane1=" + jScrollPane1 + ", jbBuscar=" + jbBuscar + ", jpanelBuscarUsuario=" + jpanelBuscarUsuario + ", jtBuscarcliente=" + jtBuscarcliente + '}';
    }

    public void setJtBuscarcliente(JButton jtBuscarcliente) {
        this.jtBuscarcliente = jtBuscarcliente;
    }

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    public JLabel getBuscar() {
        return Buscar;
    }

    public JTable getTbbuscar() {
        return jbBuscar;
    }

    public void setTbbuscar(JTable tbbuscar) {
        this.jbBuscar = tbbuscar;
    }

    public void setBuscar(JLabel Buscar) {
        this.Buscar = Buscar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelBuscarUsuario = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jtBuscarcliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbBuscar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelBuscarUsuario.setToolTipText("Buscar");

        Buscar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 255));
        Buscar.setText("Buscar");

        jtBuscarcliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtBuscarcliente.setForeground(new java.awt.Color(0, 0, 255));
        jtBuscarcliente.setText("BuscarCliente");
        jtBuscarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtBuscarclienteActionPerformed(evt);
            }
        });

        jbBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jbBuscar);

        javax.swing.GroupLayout jpanelBuscarUsuarioLayout = new javax.swing.GroupLayout(jpanelBuscarUsuario);
        jpanelBuscarUsuario.setLayout(jpanelBuscarUsuarioLayout);
        jpanelBuscarUsuarioLayout.setHorizontalGroup(
            jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                .addGroup(jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(jtBuscarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jpanelBuscarUsuarioLayout.setVerticalGroup(
            jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtBuscarcliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jpanelBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtBuscarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtBuscarclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtBuscarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbBuscar;
    private javax.swing.JPanel jpanelBuscarUsuario;
    private javax.swing.JButton jtBuscarcliente;
    // End of variables declaration//GEN-END:variables

    public JPanel getJTablaBuscarusuario() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public Object getJTablaBuscarcliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
