/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

public class Buscar extends javax.swing.JFrame {

    public JPanel getJpanelBuscarUsuario() {
        return jpanelBuscarUsuario;
    }

    public JTextField getTbBuscarCli() {
        return tbBuscarCli;
    }

    public void setTbBuscarCli(JTextField tbBuscarCli) {
        this.tbBuscarCli = tbBuscarCli;
    }

    public JTable getJbBuscar() {
        return jtTablebuscarcli;
    }

    public JTable getJtTablebuscarcli() {
        return jtTablebuscarcli;
    }

    public void setJtTablebuscarcli(JTable jtTablebuscarcli) {
        this.jtTablebuscarcli = jtTablebuscarcli;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 61 * hash + Objects.hashCode(this.jtTablebuscarcli);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Buscar other = (Buscar) obj;
        return true;
    }

    public void setJbBuscar(JTable jbBuscar) {
        this.jtTablebuscarcli = jbBuscar;
    }

    public void setJpanelBuscarUsuario(JPanel jpanelBuscarUsuario) {
        this.jpanelBuscarUsuario = jpanelBuscarUsuario;
    }

    public JTable getJtBuscarcliente() {
        return jtTablebuscarcli;
    }

    @Override
    public String toString() {
        return "Buscar{" + "Buscar=" + Buscar + ", jScrollPane1=" + jScrollPane1 + ", jbBuscar=" + jtTablebuscarcli + ", jpanelBuscarUsuario=" + jpanelBuscarUsuario + ", jtBuscarcliente=" + jtTablebuscarcli + '}';
    }

    public void setJtBuscarcliente(JButton jtBuscarcliente) {
        this.jtTablebuscarcli = jtTablebuscarcli;
    }

    /**
     * Creates new form Buscar
     */
    public Buscar() {
        initComponents();
    }

    public JLabel getBuscar() {
        return Buscar;
    }

    public JTable getTbbuscar() {
        return jtTablebuscarcli;
    }

    public void setTbbuscar(JTable tbbuscar) {
        this.jtTablebuscarcli = tbbuscar;
    }

    public void setBuscar(JLabel Buscar) {
        this.Buscar = Buscar;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelBuscarUsuario = new javax.swing.JPanel();
        Buscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablebuscarcli = new javax.swing.JTable();
        tbBuscarCli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanelBuscarUsuario.setToolTipText("Buscar");

        Buscar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Buscar.setForeground(new java.awt.Color(0, 0, 255));
        Buscar.setText("Buscar");

        jtTablebuscarcli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtTablebuscarcli);

        tbBuscarCli.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbBuscarCli.setForeground(new java.awt.Color(51, 51, 255));
        tbBuscarCli.setText("Buscar Cliente");

        javax.swing.GroupLayout jpanelBuscarUsuarioLayout = new javax.swing.GroupLayout(jpanelBuscarUsuario);
        jpanelBuscarUsuario.setLayout(jpanelBuscarUsuarioLayout);
        jpanelBuscarUsuarioLayout.setHorizontalGroup(
            jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                .addGroup(jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(tbBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jpanelBuscarUsuarioLayout.setVerticalGroup(
            jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                .addGroup(jpanelBuscarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpanelBuscarUsuarioLayout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addComponent(tbBuscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(222, 222, 222)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelBuscarUsuario;
    private javax.swing.JTable jtTablebuscarcli;
    private javax.swing.JTextField tbBuscarCli;
    // End of variables declaration//GEN-END:variables

   
    
}
