/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author sena
 */
public class FacturaCom extends javax.swing.JFrame {

    public JButton getJbguardar() {
        return jbguardar;
    }

    public JLabel getNuevaftura() {
        return nuevaftura;
    }

    public void setNuevaftura(JLabel nuevaftura) {
        this.nuevaftura = nuevaftura;
    }

    public JLabel getjLabel1() {
        return nuevaftura;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.nuevaftura = jLabel1;
    }

    public JTextField getJbtipodepago() {
        return jbtipodepago;
    }

    public void setJbtipodepago(JTextField jbtipodepago) {
        this.jbtipodepago = jbtipodepago;
    }

    public JTextField getJbtipodeprovedor() {
        return jbtipodeprovedor;
    }

    public void setJbtipodeprovedor(JTextField jbtipodeprovedor) {
        this.jbtipodeprovedor = jbtipodeprovedor;
    }

    public JTextField getTbindentificadoorusuario() {
        return tbindentificadoorusuario;
    }

    public void setTbindentificadoorusuario(JTextField tbindentificadoorusuario) {
        this.tbindentificadoorusuario = tbindentificadoorusuario;
    }

    public void setJbguardar(JButton jbguardar) {
        this.jbguardar = jbguardar;
    }

    public JLabel getJbidentiusuario() {
        return jbidentiusuario;
    }

    public void setJbidentiusuario(JLabel jbidentiusuario) {
        this.jbidentiusuario = jbidentiusuario;
    }

    public JLabel getJbideprovedor() {
        return jbideprovedor;
    }

    public void setJbideprovedor(JLabel jbideprovedor) {
        this.jbideprovedor = jbideprovedor;
    }

    public JLabel getJbtipapago() {
        return jbtipapago;
    }

    public void setJbtipapago(JLabel jbtipapago) {
        this.jbtipapago = jbtipapago;
    }

    /**
     * Creates new form FacturaCom
     */
    public FacturaCom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevaftura = new javax.swing.JLabel();
        jbtipapago = new javax.swing.JLabel();
        jbideprovedor = new javax.swing.JLabel();
        jbidentiusuario = new javax.swing.JLabel();
        jbguardar = new javax.swing.JButton();
        jbtipodepago = new javax.swing.JTextField();
        jbtipodeprovedor = new javax.swing.JTextField();
        tbindentificadoorusuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevaftura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nuevaftura.setForeground(new java.awt.Color(51, 51, 255));
        nuevaftura.setText("Nueva Factura");

        jbtipapago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtipapago.setForeground(new java.awt.Color(51, 51, 255));
        jbtipapago.setText("Tipo de pago");

        jbideprovedor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbideprovedor.setForeground(new java.awt.Color(51, 51, 255));
        jbideprovedor.setText("Identificacion del Provedor");

        jbidentiusuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbidentiusuario.setForeground(new java.awt.Color(51, 51, 255));
        jbidentiusuario.setText("Identificacion del Usuario");

        jbguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbguardar.setForeground(new java.awt.Color(51, 51, 255));
        jbguardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbidentiusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tbindentificadoorusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addComponent(jbideprovedor))
                                .addComponent(jbtipapago))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jbtipodepago)
                                .addComponent(jbtipodeprovedor)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(71, 71, 71)
                                    .addComponent(nuevaftura, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jbguardar)))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(74, 74, 74)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nuevaftura)
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtipapago)
                                .addComponent(jbtipodepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbideprovedor)
                                .addComponent(jbtipodeprovedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(31, 31, 31)
                            .addComponent(jbidentiusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(tbindentificadoorusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(93, 93, 93)
                    .addComponent(jbguardar)
                    .addContainerGap(53, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbguardar;
    private javax.swing.JLabel jbidentiusuario;
    private javax.swing.JLabel jbideprovedor;
    private javax.swing.JLabel jbtipapago;
    private javax.swing.JTextField jbtipodepago;
    private javax.swing.JTextField jbtipodeprovedor;
    private javax.swing.JLabel nuevaftura;
    private javax.swing.JTextField tbindentificadoorusuario;
    // End of variables declaration//GEN-END:variables
}
