
package Vista;

import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;



public class Nuevo_Productos extends javax.swing.JFrame {

    public JButton getJbcontra() {
        return jbcontra;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Nuevo_Productos other = (Nuevo_Productos) obj;
        if (!Objects.equals(this.btnguardar, other.btnguardar)) {
            return false;
        }
        if (!Objects.equals(this.jPanel1, other.jPanel1)) {
            return false;
        }
        if (!Objects.equals(this.jScrollPane2, other.jScrollPane2)) {
            return false;
        }
        if (!Objects.equals(this.jbcontra, other.jbcontra)) {
            return false;
        }
        if (!Objects.equals(this.jbimagen, other.jbimagen)) {
            return false;
        }
        if (!Objects.equals(this.jbnnombre, other.jbnnombre)) {
            return false;
        }
        if (!Objects.equals(this.jtnombre, other.jtnombre)) {
            return false;
        }
        if (!Objects.equals(this.jbpro, other.jbpro)) {
            return false;
        }
        if (!Objects.equals(this.jtbdescrp, other.jtbdescrp)) {
            return false;
        }
        if (!Objects.equals(this.jtbdespcrip, other.jtbdespcrip)) {
            return false;
        }
        return Objects.equals(this.jtbimagen, other.jtbimagen);
    }

    public JLabel getJbimagen() {
        return jbimagen;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getJtnombre() {
        return jtnombre;
    }

    public void setJtnombre(JLabel jtnombre) {
        this.jtnombre = jtnombre;
    }

    public void setJbimagen(JLabel jbimagen) {
        this.jbimagen = jbimagen;
    }

    public JLabel getJbnombr() {
        return jtnombre;
    }

    public void setJbnombr(JLabel jbnombr) {
        this.jtnombre = jbnombr;
    }

    public JLabel getJbpro() {
        return jbpro;
    }

    public void setJbpro(JLabel jbpro) {
        this.jbpro = jbpro;
    }

    public JButton getBtncancelar() {
        return btncancelar;
    }

    public void setBtncancelar(JButton btncancelar) {
        this.btncancelar = btncancelar;
    }

    public void setJbcontra(JButton jbcontra) {
        this.jbcontra = jbcontra;
    }

    public JLabel getJtbdescrp() {
        return jtbdescrp;
    }

    public void setJtbdescrp(JLabel jtbdescrp) {
        this.jtbdescrp = jtbdescrp;
    }

    /**
     * Creates new form NuevoProducto
     */
    public Nuevo_Productos() {
        initComponents();
    }

    public JButton getBtnguardar() {
        return btnguardar;
    }

    public void setBtnguardar(JButton btnguardar) {
        this.btnguardar = btnguardar;
    }

    public JButton getjButton2() {
        return jbcontra;
    }

    public void setjButton2(JButton jButton2) {
        this.jbcontra = jButton2;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JTextField getJbnnombre() {
        return jbnnombre;
    }

    public void setJbnnombre(JTextField jbnnombre) {
        this.jbnnombre = jbnnombre;
    }

    public JTextField getTfidescrip() {
        return tfidescrip;
    }

    public void setTfidescrip(JTextField tfidescrip) {
        this.tfidescrip = tfidescrip;
    }

    public JTextArea getJtbdespcrip() {
        return jtbdespcrip;
    }

    public void setJtbdespcrip(JTextArea jtbdespcrip) {
        this.jtbdespcrip = jtbdespcrip;
    }

    public JTextField getJtbimagen() {
        return jtbimagen;
    }

    public void setJtbimagen(JTextField jtbimagen) {
        this.jtbimagen = jtbimagen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jtbdespcrip = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbpro = new javax.swing.JLabel();
        jtnombre = new javax.swing.JLabel();
        jbimagen = new javax.swing.JLabel();
        jtbdescrp = new javax.swing.JLabel();
        jbnnombre = new javax.swing.JTextField();
        jtbimagen = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jbcontra = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        tfidescrip = new javax.swing.JTextField();

        jtbdespcrip.setColumns(20);
        jtbdespcrip.setForeground(new java.awt.Color(51, 51, 255));
        jtbdespcrip.setRows(5);
        jScrollPane2.setViewportView(jtbdespcrip);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbpro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbpro.setForeground(new java.awt.Color(102, 102, 255));
        jbpro.setText("Nuevo  Producto");

        jtnombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtnombre.setForeground(new java.awt.Color(51, 51, 255));
        jtnombre.setText("Nombre");

        jbimagen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbimagen.setForeground(new java.awt.Color(51, 51, 255));
        jbimagen.setText("Imagen");

        jtbdescrp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbdescrp.setForeground(new java.awt.Color(51, 51, 255));
        jtbdescrp.setText("Descripcion");

        jbnnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnnombreActionPerformed(evt);
            }
        });

        btnguardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(51, 51, 255));
        btnguardar.setText("Guardar");

        jbcontra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yeimar2.jpg"))); // NOI18N

        btncancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(0, 0, 255));
        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbpro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbdescrp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbnnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfidescrip, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jbpro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbnnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtbimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbdescrp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfidescrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbnnombreActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbcontra;
    private javax.swing.JLabel jbimagen;
    private javax.swing.JTextField jbnnombre;
    private javax.swing.JLabel jbpro;
    private javax.swing.JLabel jtbdescrp;
    private javax.swing.JTextArea jtbdespcrip;
    private javax.swing.JTextField jtbimagen;
    private javax.swing.JLabel jtnombre;
    private javax.swing.JTextField tfidescrip;
    // End of variables declaration//GEN-END:variables

  
}
